name: Deployment From Github to AWS
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Latest Repo
        uses: actions/checkout@main
        
      - name: Generate Deployment Package
        run: zip -r deploy.zip * -x "**node_modules**"
        
      - name: Deploy to EB
        uses: einaregilsson/beanstalk@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          application_name: simple-engineer-deployment-tutorial
          environment_name: Simpleengineerdeploymenttutorial-env
          version_label: ${{ github.sha }}
          region: us-west-2
          deployment_package: deploy.zip
